# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0_Lc1ievfsIVcwyItbypibh_ydusbm3
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import math
from tqdm import tqdm

# ------------------------------
# 1. Neural 1‑Form (core)
# ------------------------------
class NeuralOneForm(nn.Module):
    def __init__(self, d_model, hidden_dim=16):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(d_model, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, d_model)
        )

    def forward(self, x):
        return self.net(x)

def line_integral_1form(form_mlp, p, q, samples=3):
    device = p.device
    if samples == 3:
        nodes = torch.tensor([0.1127016654, 0.5, 0.8872983346], device=device)
        weights = torch.tensor([0.2777777778, 0.4444444444, 0.2777777778], device=device)
    else:
        nodes = torch.linspace(0, 1, samples, device=device)
        weights = torch.full((samples,), 1.0/samples, device=device)
    direction = q - p
    integral = torch.zeros(p.shape[0], device=device)
    for node, w in zip(nodes, weights):
        t = node
        point = (1 - t) * p + t * q
        vec = form_mlp(point)
        integral += w * torch.sum(vec * direction, dim=-1)
    return integral

# ------------------------------
# 2. Minimal Attention (single head, no FFN, no LayerNorm)
# ------------------------------
class MinimalNeuralFormAttention(nn.Module):
    def __init__(self, d_model, hidden_dim=16):
        super().__init__()
        self.form = NeuralOneForm(d_model, hidden_dim)
        self.w_v = nn.Linear(d_model, d_model)
        self.w_o = nn.Linear(d_model, d_model)

    def forward(self, x, memory=None, mask=None):
        """
        x: (batch, q_len, d_model) – queries
        memory: (batch, kv_len, d_model) – keys/values; if None, use x (self-attention)
        mask: additive mask (e.g., causal)
        """
        batch, q_len, d_model = x.shape
        if memory is None:
            kv = x
        else:
            kv = memory
        kv_len = kv.shape[1]

        # Project values
        V = self.w_v(kv)  # (batch, kv_len, d_model)

        # Compute line‑integral scores (single head)
        scores = torch.zeros(batch, q_len, kv_len, device=x.device)
        form = self.form
        for i in range(q_len):
            p = x[:, i, :]
            for j in range(kv_len):
                q = kv[:, j, :]
                integral = line_integral_1form(form, p, q)
                scores[:, i, j] = integral

        if mask is not None:
            scores = scores + mask

        scores = scores / math.sqrt(d_model)  # scale
        attn = F.softmax(scores, dim=-1)      # (batch, q_len, kv_len)

        # Aggregate values
        out = torch.matmul(attn, V)           # (batch, q_len, d_model)
        out = self.w_o(out)
        return out

# ------------------------------
# 3. Minimal Seq2Seq Model
# ------------------------------
class MinimalNeuralFormSeq2Seq(nn.Module):
    def __init__(self, vocab_size, pad_token_id, d_model=16, hidden_dim=16, max_len=16):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model, padding_idx=pad_token_id)
        self.pos_encoding = nn.Parameter(torch.randn(1, max_len, d_model) * 0.01)
        self.max_len = max_len
        self.pad_token_id = pad_token_id

        # Encoder self‑attention (no mask – bidirectional)
        self.enc_attn = MinimalNeuralFormAttention(d_model, hidden_dim)
        # Decoder self‑attention (causal mask applied inside)
        self.dec_attn = MinimalNeuralFormAttention(d_model, hidden_dim)
        # Cross‑attention (decoder queries, encoder keys/values)
        self.cross_attn = MinimalNeuralFormAttention(d_model, hidden_dim)

        self.head = nn.Linear(d_model, vocab_size)

    def forward(self, encoder_ids, decoder_ids):
        # ---- Encoder ----
        enc_seq_len = encoder_ids.size(1)
        enc_pos = self.pos_encoding[:, :enc_seq_len, :]
        enc_x = self.embedding(encoder_ids) + enc_pos
        # No mask – bidirectional
        enc_x = self.enc_attn(enc_x, memory=None, mask=None)   # self‑attention

        # ---- Decoder ----
        dec_seq_len = decoder_ids.size(1)
        dec_pos = self.pos_encoding[:, :dec_seq_len, :]
        dec_x = self.embedding(decoder_ids) + dec_pos

        # Causal mask for decoder self‑attention
        causal_mask = torch.triu(torch.ones(dec_seq_len, dec_seq_len, device=decoder_ids.device), diagonal=1) * -1e9
        # Padding mask (ignore pad tokens)
        pad_mask = (decoder_ids == self.pad_token_id).float() * -1e9
        pad_mask = pad_mask.unsqueeze(1)  # (batch, 1, dec_seq_len)
        self_mask = causal_mask.unsqueeze(0) + pad_mask   # (batch, dec_len, dec_len)

        # Decoder self‑attention
        dec_x = self.dec_attn(dec_x, memory=None, mask=self_mask)

        # Cross‑attention: queries = dec_x, keys/values = enc_x
        # Encoder padding mask for cross‑attention
        enc_pad_mask = (encoder_ids == self.pad_token_id).float() * -1e9
        enc_pad_mask = enc_pad_mask.unsqueeze(1)  # (batch, 1, enc_len)
        # Broadcast to (batch, dec_len, enc_len)
        cross_mask = enc_pad_mask.expand(-1, dec_seq_len, -1)

        dec_x = self.cross_attn(dec_x, memory=enc_x, mask=cross_mask)

        logits = self.head(dec_x)   # (batch, dec_seq_len, vocab_size)
        return logits

# ------------------------------
# 4. Dummy Dataset (same as before)
# ------------------------------
class SimpleTokenizer:
    def __init__(self):
        self.vocab = {'<pad>':0, '<unk>':1, '<bos>':2, '<eos>':3}
        self.pad_token_id = 0
        self.unk_token_id = 1
        self.bos_token_id = 2
        self.eos_token_id = 3
        self.idx2word = {0:'<pad>', 1:'<unk>', 2:'<bos>', 3:'<eos>'}

    def add_words(self, sentences):
        for sent in sentences:
            for w in sent.split():
                if w not in self.vocab:
                    self.vocab[w] = len(self.vocab)
                    self.idx2word[self.vocab[w]] = w

    def encode(self, text, add_bos=False, add_eos=False):
        ids = [self.vocab.get(w, self.unk_token_id) for w in text.split()]
        if add_bos:
            ids = [self.bos_token_id] + ids
        if add_eos:
            ids = ids + [self.eos_token_id]
        return ids

    def decode(self, ids, skip_special=False):
        words = []
        for i in ids:
            w = self.idx2word.get(i, '<unk>')
            if skip_special and w in ('<pad>','<unk>','<bos>','<eos>'):
                continue
            words.append(w)
        return ' '.join(words)

def build_dummy_data():
    qa_pairs = [
        ("What is the capital of France?", "Paris"),
        ("Who wrote Hamlet?", "Shakespeare"),
        ("What is 2+2?", "4"),
        ("What is the largest planet?", "Jupiter"),
        ("What is the smallest country?", "Vatican"),
    ]
    return qa_pairs

class QADataset(Dataset):
    def __init__(self, qa_pairs, tokenizer, max_len=10):
        self.pairs = qa_pairs
        self.tokenizer = tokenizer
        self.max_len = max_len
        all_text = [q + " " + a for q, a in qa_pairs]
        tokenizer.add_words(all_text)

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        question, answer = self.pairs[idx]
        enc_ids = self.tokenizer.encode(question, add_bos=False, add_eos=False)
        enc_ids = enc_ids[:self.max_len]
        enc_len = len(enc_ids)
        enc_ids = enc_ids + [self.tokenizer.pad_token_id] * (self.max_len - enc_len)

        dec_input = self.tokenizer.encode(answer, add_bos=True, add_eos=False)
        dec_input = dec_input[:self.max_len-1]
        dec_len = len(dec_input)
        dec_input = dec_input + [self.tokenizer.pad_token_id] * (self.max_len - dec_len)

        dec_target = self.tokenizer.encode(answer, add_bos=False, add_eos=True)
        dec_target = dec_target[:self.max_len]
        dec_target = dec_target + [self.tokenizer.pad_token_id] * (self.max_len - len(dec_target))

        return (torch.tensor(enc_ids, dtype=torch.long),
                torch.tensor(dec_input, dtype=torch.long),
                torch.tensor(dec_target, dtype=torch.long))

def collate_fn(batch):
    enc_ids, dec_input, dec_target = zip(*batch)
    return (torch.stack(enc_ids), torch.stack(dec_input), torch.stack(dec_target))

# ------------------------------
# 5. Training and Generation
# ------------------------------
def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    total_tokens = 0
    for enc_ids, dec_input, dec_target in tqdm(loader, desc='Training'):
        enc_ids, dec_input, dec_target = enc_ids.to(device), dec_input.to(device), dec_target.to(device)
        optimizer.zero_grad()
        logits = model(enc_ids, dec_input)
        loss = criterion(logits.view(-1, logits.size(-1)), dec_target.view(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item() * dec_target.numel()
        total_tokens += (dec_target != tokenizer.pad_token_id).sum().item()
    return total_loss / total_tokens

@torch.no_grad()
def generate(model, tokenizer, question, max_new_tokens=10, temperature=0.8, device='cpu'):
    model.eval()
    enc_ids = tokenizer.encode(question, add_bos=False, add_eos=False)
    enc_ids = enc_ids[:model.max_len]
    enc_ids = enc_ids + [tokenizer.pad_token_id] * (model.max_len - len(enc_ids))
    enc_ids = torch.tensor([enc_ids], device=device)

    dec_input = torch.tensor([[tokenizer.bos_token_id]], device=device)
    for _ in range(max_new_tokens):
        curr_len = dec_input.size(1)
        if curr_len < model.max_len:
            pad = torch.full((1, model.max_len - curr_len), tokenizer.pad_token_id, device=device)
            dec_full = torch.cat([dec_input, pad], dim=1)
        else:
            dec_full = dec_input[:, -model.max_len:]
        logits = model(enc_ids, dec_full)
        next_token_logits = logits[0, curr_len-1, :] / temperature
        probs = F.softmax(next_token_logits, dim=-1)
        next_token = torch.multinomial(probs, 1).item()
        if next_token == tokenizer.eos_token_id:
            break
        dec_input = torch.cat([dec_input, torch.tensor([[next_token]], device=device)], dim=1)
    return tokenizer.decode(dec_input[0].tolist(), skip_special=True)

# ------------------------------
# 6. Main
# ------------------------------
if __name__ == '__main__':
    tokenizer = SimpleTokenizer()
    qa_pairs = build_dummy_data()
    dataset = QADataset(qa_pairs, tokenizer, max_len=10)
    loader = DataLoader(dataset, batch_size=4, shuffle=True, collate_fn=collate_fn)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    vocab_size = len(tokenizer.vocab)
    pad_id = tokenizer.pad_token_id

    model = MinimalNeuralFormSeq2Seq(
        vocab_size=vocab_size,
        pad_token_id=pad_id,
        d_model=16,
        hidden_dim=16,
        max_len=10
    ).to(device)

    optimizer = optim.AdamW(model.parameters(), lr=1e-2)
    criterion = nn.CrossEntropyLoss(ignore_index=pad_id)

    print("Training minimal model...")
    for epoch in range(50):
        loss = train_epoch(model, loader, optimizer, criterion, device)
        print(f"Epoch {epoch+1}: Loss = {loss:.4f}")

    q = "What is the capital of France?"
    ans = generate(model, tokenizer, q, device=device)
    print(f"\nQ: {q}\nA: {ans}")

    q = "Who wrote Hamlet?"
    ans = generate(model, tokenizer, q, device=device)
    print(f"\nQ: {q}\nA: {ans}")

    q = "AI is"
    ans = generate(model, tokenizer, q, device=device)
    print(f"\nQ: {q}\nA: {ans}")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import math
import random
from tqdm import tqdm

# ------------------------------
# 1. Non‑Commutative Differential Form
# ------------------------------
class NonCommutativeOneForm(nn.Module):
    def __init__(self, d_model, hidden_dim=32):
        super().__init__()
        self.d_model = d_model
        self.net = nn.Sequential(
            nn.Linear(d_model, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, d_model * d_model)
        )
        for m in self.net.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight, gain=0.01)
                nn.init.zeros_(m.bias)

    def forward(self, x):
        flat = self.net(x)
        flat = torch.clamp(flat, min=-5.0, max=5.0)
        return flat.view(x.size(0), self.d_model, self.d_model)

# ------------------------------
# 2. Causal Non‑Commutative Attention
# ------------------------------
class CausalNonCommutativeAttention(nn.Module):
    def __init__(self, d_model, hidden_dim=32):
        super().__init__()
        self.form = NonCommutativeOneForm(d_model, hidden_dim)
        self.w_v = nn.Linear(d_model, d_model)
        self.w_o = nn.Linear(d_model, d_model)
        self.temp = nn.Parameter(torch.ones(1) * 0.5)
        self.register_buffer('nodes', torch.tensor([0.1127, 0.5, 0.8873]))
        self.register_buffer('weights', torch.tensor([0.2778, 0.4444, 0.2778]))

    def forward(self, x, mask=None):
        """
        x: (batch, seq_len, d_model)
        mask: (batch, seq_len, seq_len) with -inf for future positions
        """
        batch, seq_len, d = x.shape
        kv = x  # self‑attention: keys and values are the same as queries
        V = self.w_v(kv)
        out = torch.zeros(batch, seq_len, d, device=x.device)

        for i in range(seq_len):
            p = x[:, i, :]                       # (batch, d)
            P = p.unsqueeze(1).expand(-1, seq_len, -1)   # (batch, seq_len, d)
            Q = kv
            direction = Q - P
            step_norm = torch.norm(direction, dim=-1, keepdim=True)

            batch_seq = batch * seq_len
            P_flat = P.reshape(batch_seq, d)
            Q_flat = Q.reshape(batch_seq, d)
            direction_flat = direction.reshape(batch_seq, d)
            step_norm_flat = step_norm.reshape(batch_seq, 1, 1)

            U = torch.eye(d, device=x.device).unsqueeze(0).expand(batch_seq, -1, -1)

            for node, w in zip(self.nodes, self.weights):
                mid = (1 - node) * P_flat + node * Q_flat
                A_mat = self.form(mid).reshape(batch_seq, d, d)
                term = A_mat * (w * step_norm_flat)
                term = torch.clamp(term, min=-10.0, max=10.0)
                exp_term = torch.matrix_exp(term)
                U = torch.bmm(exp_term, U)

            U = U.reshape(batch, seq_len, d, d)
            scores = torch.diagonal(U, dim1=-2, dim2=-1).sum(-1)   # (batch, seq_len)

            if mask is not None:
                row_mask = mask[:, i, :]  # (batch, seq_len)
                scores = scores + row_mask

            scores = scores / (self.temp.abs() + 1e-6)
            scores = torch.clamp(scores, min=-50.0, max=50.0)
            attn = F.softmax(scores, dim=-1)   # (batch, seq_len)

            # Transform values with U
            V_flat = V.reshape(batch_seq, d, 1)
            U_flat = U.reshape(batch_seq, d, d)
            transformed_v = torch.bmm(U_flat, V_flat).reshape(batch, seq_len, d)

            out[:, i, :] = torch.sum(attn.unsqueeze(-1) * transformed_v, dim=1)

        out = self.w_o(out)
        out = out + x  # residual
        return out

# ------------------------------
# 3. Decoder‑Only Non‑Commutative Model
# ------------------------------
class DecoderOnlyNonCommutative(nn.Module):
    def __init__(self, vocab_size, d_model=16, hidden_dim=32, max_len=16):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = nn.Parameter(torch.randn(1, max_len, d_model) * 0.01)
        self.attn = CausalNonCommutativeAttention(d_model, hidden_dim)
        self.head = nn.Linear(d_model, vocab_size)
        self.max_len = max_len

    def forward(self, input_ids):
        seq_len = input_ids.size(1)
        x = self.embedding(input_ids) + self.pos_encoding[:, :seq_len, :]
        # Causal mask: upper triangular with -1e9
        mask = torch.triu(torch.ones(seq_len, seq_len, device=input_ids.device), diagonal=1) * -1e9
        mask = mask.unsqueeze(0)  # (1, seq_len, seq_len)
        x = self.attn(x, mask=mask)
        logits = self.head(x)
        return logits

# ------------------------------
# 4. Dummy Data: next‑integer prediction
# ------------------------------
class ArithmeticDataset(Dataset):
    def __init__(self, num_samples=1000, vocab_size=20, seq_len=8):
        self.num_samples = num_samples
        self.vocab_size = vocab_size
        self.seq_len = seq_len
        self.data = []
        for _ in range(num_samples):
            # Generate a sequence of integers with a pattern: start random, then increment by 1
            start = random.randint(0, vocab_size - seq_len - 2)  # ensure room
            seq = list(range(start, start + seq_len))
            self.data.append(torch.tensor(seq, dtype=torch.long))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        seq = self.data[idx]
        # input: first seq_len-1 tokens, target: shifted by 1 (next token)
        return seq[:-1], seq[1:]

def collate_fn(batch):
    inputs, targets = zip(*batch)
    max_len = max(len(inp) for inp in inputs)
    # Pad with 0 (assuming 0 is a valid token, but we'll treat 0 as pad)
    padded_inputs = []
    padded_targets = []
    for inp, tgt in zip(inputs, targets):
        pad_len = max_len - len(inp)
        padded_inputs.append(torch.cat([inp, torch.zeros(pad_len, dtype=torch.long)]))
        padded_targets.append(torch.cat([tgt, torch.zeros(pad_len, dtype=torch.long)]))
    return torch.stack(padded_inputs), torch.stack(padded_targets)

# ------------------------------
# 5. Training
# ------------------------------
def train_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0
    total_tokens = 0
    for inputs, targets in tqdm(loader, desc='Training'):
        inputs, targets = inputs.to(device), targets.to(device)
        optimizer.zero_grad()
        logits = model(inputs)
        loss = criterion(logits.view(-1, logits.size(-1)), targets.view(-1))
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        total_loss += loss.item() * targets.numel()
        total_tokens += (targets != 0).sum().item()
    return total_loss / total_tokens

# ------------------------------
# 6. Generation (autoregressive)
# ------------------------------
@torch.no_grad()
def generate(model, start_tokens, max_new_tokens=5, temperature=0.8, device='cpu'):
    model.eval()
    input_ids = start_tokens.to(device)  # (1, seq_len)
    for _ in range(max_new_tokens):
        # If sequence grows beyond max_len, crop to last max_len tokens
        if input_ids.size(1) > model.max_len:
            input_ids = input_ids[:, -model.max_len:]
        logits = model(input_ids)
        next_token_logits = logits[0, -1, :] / temperature
        probs = F.softmax(next_token_logits, dim=-1)
        next_token = torch.multinomial(probs, 1).item()
        input_ids = torch.cat([input_ids, torch.tensor([[next_token]], device=device)], dim=1)
    return input_ids

# ------------------------------
# 7. Main
# ------------------------------
if __name__ == '__main__':
    vocab_size = 30      # numbers 0..29
    seq_len = 8
    d_model = 16
    hidden_dim = 32
    batch_size = 32
    epochs = 20

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    # Data
    dataset = ArithmeticDataset(num_samples=2000, vocab_size=vocab_size, seq_len=seq_len)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)

    model = DecoderOnlyNonCommutative(vocab_size, d_model, hidden_dim, max_len=seq_len).to(device)
    print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")

    optimizer = optim.AdamW(model.parameters(), lr=1e-3)
    criterion = nn.CrossEntropyLoss(ignore_index=0)  # ignore padding (token 0)

    for epoch in range(1, epochs+1):
        loss = train_epoch(model, loader, optimizer, criterion, device)
        print(f"Epoch {epoch}: Loss = {loss:.4f}")

        # Test generation
        start = torch.tensor([[5, 6, 7, 8]], dtype=torch.long)  # known pattern
        gen = generate(model, start, max_new_tokens=5, temperature=0.8, device=device)
        print(f"Start: {start.tolist()} -> Generated: {gen.tolist()}")

